name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
            2.1.x
            3.1.x
            6.0.x
    - name: Remove signing
      run: |
        dotnet tool install --global replace-in-file 
        replace-in-file ./NLoptNet/NLoptNet.csproj -set "SignAssembly>true" "SignAssembly>false" -set "TargetFrameworks" "TargetFramework" -set ";net47" ""
        replace-in-file ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj -set "net47;net48;" ""
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release /p:PackageVersion=0.0.0-local
    - name: Test package
      run: |
        dotnet nuget add source ${{ github.workspace }}/pack -n="LocalNLopt"
        dotnet test ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj -c Release /property:Platform="AnyCPU" 
        dotnet test ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj -c Release /property:Platform="x64"