name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
            3.1.x
            6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release /p:PackageVersion=0.0.0-local
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Test package
      run: |
        dotnet nuget add source ${{ github.workspace }}/pack -n="LocalNLopt"
        dotnet test ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj -c Release /property:Platform="AnyCPU" 
        dotnet test ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj -c Release /property:Platform="x64"